-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 16:29:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema azcme_uam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `azcme_uam` ;

-- -----------------------------------------------------
-- Schema azcme_uam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `azcme_uam` DEFAULT CHARACTER SET utf8 ;
USE `azcme_uam` ;

-- -----------------------------------------------------
-- Table `azcme_uam`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`admin` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`admin` (
  `idAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NULL DEFAULT NULL,
  `apellidoM` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`autor` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`autor` (
  `idAutor` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`tipomaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`tipomaterial` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`tipomaterial` (
  `idTipoMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMaterial`),
  UNIQUE INDEX `Descripcion_UNIQUE` (`Descripcion` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`material` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`material` (
  `idMaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `URL` VARCHAR(45) NULL,
  `FechaPublicacion` DATE NULL DEFAULT NULL,
  `tipomaterial_idTipoMaterial` INT(11) NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_material_tipomaterial1_idx` (`tipomaterial_idTipoMaterial` ASC) ,
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC) ,
  CONSTRAINT `fk_material_tipomaterial1`
    FOREIGN KEY (`tipomaterial_idTipoMaterial`)
    REFERENCES `azcme_uam`.`tipomaterial` (`idTipoMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`material_has_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`material_has_autor` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`material_has_autor` (
  `id_M_A` INT(11) NOT NULL AUTO_INCREMENT,
  `Material_idMaterial` INT(11) NOT NULL,
  `Autor_idAutor` INT(11) NOT NULL,
  PRIMARY KEY (`id_M_A`),
  INDEX `fk_Material_has_Autor_Material` (`Material_idMaterial` ASC) ,
  INDEX `fk_Material_has_Autor_Autor1` (`Autor_idAutor` ASC) ,
  CONSTRAINT `fk_Material_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `azcme_uam`.`autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Autor_Material`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `azcme_uam`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`palabraclave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`palabraclave` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`palabraclave` (
  `idPalabraClave` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPalabraClave`),
  UNIQUE INDEX `Descripcion_UNIQUE` (`Descripcion` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`palabraclave_has_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`palabraclave_has_material` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`palabraclave_has_material` (
  `id_PC_M` INT(11) NOT NULL AUTO_INCREMENT,
  `PalabraClave_idPalabraClave` INT(11) NOT NULL,
  `Material_idMaterial` INT(11) NOT NULL,
  PRIMARY KEY (`id_PC_M`),
  INDEX `fk_PalabraClave_has_Material_PalabraClave1` (`PalabraClave_idPalabraClave` ASC) ,
  INDEX `fk_PalabraClave_has_Material_Material1` (`Material_idMaterial` ASC) ,
  CONSTRAINT `fk_PalabraClave_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `azcme_uam`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PalabraClave_has_Material_PalabraClave1`
    FOREIGN KEY (`PalabraClave_idPalabraClave`)
    REFERENCES `azcme_uam`.`palabraclave` (`idPalabraClave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`uea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`uea` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`uea` (
  `idUEA` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreUEA` VARCHAR(45) NOT NULL,
  `claveUEA` INT(11) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idUEA`),
  UNIQUE INDEX `claveUEA_UNIQUE` (`claveUEA` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`temario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`temario` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`temario` (
  `idTemario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `UEA_idUEA` INT(11) NOT NULL,
  PRIMARY KEY (`idTemario`),
  INDEX `fk_Temario_UEA1` (`UEA_idUEA` ASC) ,
  CONSTRAINT `fk_Temario_UEA1`
    FOREIGN KEY (`UEA_idUEA`)
    REFERENCES `azcme_uam`.`uea` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`tema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`tema` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`tema` (
  `idTema` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Temario_idTemario` INT(11) NOT NULL,
  PRIMARY KEY (`idTema`),
  INDEX `fk_Tema_Temario1` (`Temario_idTemario` ASC) ,
  CONSTRAINT `fk_Tema_Temario1`
    FOREIGN KEY (`Temario_idTemario`)
    REFERENCES `azcme_uam`.`temario` (`idTemario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `azcme_uam`.`material_has_tema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `azcme_uam`.`material_has_tema` ;

CREATE TABLE IF NOT EXISTS `azcme_uam`.`material_has_tema` (
  `id_M_T` INT NOT NULL AUTO_INCREMENT,
  `material_idMaterial` INT(11) NOT NULL,
  `tema_idTema` INT(11) NOT NULL,
  INDEX `fk_material_has_tema_tema1_idx` (`tema_idTema` ASC) ,
  INDEX `fk_material_has_tema_material1_idx` (`material_idMaterial` ASC) ,
  PRIMARY KEY (`id_M_T`),
  CONSTRAINT `fk_material_has_tema_material1`
    FOREIGN KEY (`material_idMaterial`)
    REFERENCES `azcme_uam`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_has_tema_tema1`
    FOREIGN KEY (`tema_idTema`)
    REFERENCES `azcme_uam`.`tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*** INSERCIONES NECESARIAS ***/
Insert into admin (usuario,contrasena,nombre,apellidoP,apellidoM) values ('admin','admin','admin1','admin1','admin1');
Insert into tipomaterial (descripcion) values ('PDFs');
Insert into tipomaterial (descripcion) values ('Video Youtube');
Insert into tipomaterial (descripcion) values ('Libro BiDiUAM');
